import { DocsClasslistMap } from 'types';
import { CategoryClassnames, CategoryClasses } from './types';

export const classnames = [
  'FGBuildable',
  'FGBuildableAttachmentMerger',
  'FGBuildableAttachmentSplitter',
  'FGBuildableCircuitSwitch',
  'FGBuildableConveyorBelt',
  'FGBuildableConveyorLift',
  'FGBuildableDockingStation',
  'FGBuildableDroneStation',
  'FGBuildableFactory',
  'FGBuildableFactorySimpleProducer',
  'FGBuildableFloodlight',
  'FGBuildableFoundation',
  'FGBuildableFrackingActivator',
  'FGBuildableFrackingExtractor',
  'FGBuildableGeneratorFuel',
  'FGBuildableGeneratorGeoThermal',
  'FGBuildableGeneratorNuclear',
  'FGBuildableJumppad',
  'FGBuildableLadder',
  'FGBuildableLightSource',
  'FGBuildableLightsControlPanel',
  'FGBuildableMAM',
  'FGBuildableManufacturer',
  'FGBuildableManufacturerVariablePower',
  'FGBuildablePipeHyper',
  'FGBuildablePipeReservoir',
  'FGBuildablePipeline',
  'FGBuildablePipelineJunction',
  'FGBuildablePipelinePump',
  'FGBuildablePipelineSupport',
  'FGBuildablePole',
  'FGBuildablePowerPole',
  'FGBuildablePowerStorage',
  'FGBuildableRadarTower',
  'FGBuildableRailroadStation',
  'FGBuildableRailroadTrack',
  'FGBuildableResourceExtractor',
  'FGBuildableResourceSink',
  'FGBuildableResourceSinkShop',
  'FGBuildableSnowDispenser',
  'FGBuildableSpaceElevator',
  'FGBuildableSplitterSmart',
  'FGBuildableStair',
  'FGBuildableStorage',
  'FGBuildableTradingPost',
  'FGBuildableTrainPlatformCargo',
  'FGBuildableTrainPlatformEmpty',
  'FGBuildableWalkway',
  'FGBuildableWall',
  'FGBuildableWaterPump',
  'FGBuildableWire',
  'FGBuildingDescriptor',
  'FGChainsaw',
  'FGColorGun',
  'FGConsumableDescriptor',
  'FGConsumableEquipment',
  'FGConveyorPoleStackable',
  'FGEquipmentDescriptor',
  'FGEquipmentStunSpear',
  'FGEquipmentZipline',
  'FGGasMask',
  'FGGolfCartDispenser',
  'FGHoverPack',
  'FGItemDescriptor',
  'FGItemDescriptorBiomass',
  'FGItemDescriptorNuclearFuel',
  'FGJetPack',
  'FGJumpingStilts',
  'FGNobeliskDetonator',
  'FGObjectScanner',
  'FGParachute',
  'FGPipeHyperStart',
  'FGPoleDescriptor',
  'FGPortableMinerDispenser',
  'FGRecipe',
  'FGResourceDescriptor',
  'FGSchematic',
  'FGSnowballWeapon',
  'FGSuitBase',
  'FGVehicleDescriptor',
  'FGWeaponInstantFire',
  'FGWeaponProjectileFire',
];

export const categoryClassnames: CategoryClassnames = {
  itemDescriptors: [
    'FGConsumableDescriptor',
    'FGEquipmentDescriptor',
    'FGItemDescriptor',
    'FGItemDescriptorBiomass',
    'FGItemDescriptorNuclearFuel',
    'FGResourceDescriptor',
  ],
  resources: [
    'FGResourceDescriptor',
  ],
  consumables: [
    'FGConsumableDescriptor',
  ],
  equipment: [
    'FGChainsaw',
    'FGColorGun',
    'FGConsumableEquipment',
    'FGEquipmentStunSpear',
    'FGEquipmentZipline',
    'FGGasMask',
    'FGGolfCartDispenser',
    'FGHoverPack',
    'FGJetPack',
    'FGJumpingStilts',
    'FGNobeliskDetonator',
    'FGObjectScanner',
    'FGParachute',
    'FGPortableMinerDispenser',
    'FGSnowballWeapon',
    'FGSuitBase',
    'FGWeaponInstantFire',
    'FGWeaponProjectileFire'
  ],

  buildingDescriptors: [
    'FGBuildingDescriptor',
    'FGPoleDescriptor',
  ],
  vehicles: [
    'FGVehicleDescriptor',
  ],
  buildings: [
    'FGBuildable',
    'FGBuildableAttachmentMerger',
    'FGBuildableAttachmentSplitter',
    'FGBuildableCircuitSwitch',
    'FGBuildableConveyorBelt',
    'FGBuildableConveyorLift',
    'FGBuildableDockingStation',
    'FGBuildableDroneStation',
    'FGBuildableFactory',
    'FGBuildableFactorySimpleProducer',
    'FGBuildableFloodlight',
    'FGBuildableFoundation',
    'FGBuildableFrackingActivator',
    'FGBuildableFrackingExtractor',
    'FGBuildableGeneratorFuel',
    'FGBuildableGeneratorGeoThermal',
    'FGBuildableGeneratorNuclear',
    'FGBuildableJumppad',
    'FGBuildableLadder',
    'FGBuildableLightSource',
    'FGBuildableLightsControlPanel',
    'FGBuildableMAM',
    'FGBuildableManufacturer',
    'FGBuildableManufacturerVariablePower',
    'FGBuildablePipeHyper',
    'FGBuildablePipeReservoir',
    'FGBuildablePipeline',
    'FGBuildablePipelineJunction',
    'FGBuildablePipelinePump',
    'FGBuildablePipelineSupport',
    'FGBuildablePole',
    'FGBuildablePowerPole',
    'FGBuildablePowerStorage',
    'FGBuildableRadarTower',
    'FGBuildableRailroadStation',
    'FGBuildableRailroadTrack',
    'FGBuildableResourceExtractor',
    'FGBuildableResourceSink',
    'FGBuildableResourceSinkShop',
    'FGBuildableSnowDispenser',
    'FGBuildableSpaceElevator',
    'FGBuildableSplitterSmart',
    'FGBuildableStair',
    'FGBuildableStorage',
    'FGBuildableTradingPost',
    'FGBuildableTrainPlatformCargo',
    'FGBuildableTrainPlatformEmpty',
    'FGBuildableWalkway',
    'FGBuildableWall',
    'FGBuildableWaterPump',
    'FGBuildableWire',
    'FGConveyorPoleStackable',
    'FGPipeHyperStart',
  ],

  recipes: [
    'FGRecipe',
  ],

  schematics: [
    'FGSchematic',
  ],
};

export function getCategoryClasses(classlistMap: DocsClasslistMap): CategoryClasses {
  const categoryClasses: any = {};
  Object.entries(categoryClassnames).forEach(([category, classnames]) => {
    categoryClasses[category] = classnames.flatMap((classname) => classlistMap[classname]);
  });
  return (categoryClasses as CategoryClasses);
}
